version: "3.2"
services:
    mssql-2022:
        container_name: mssql-2022
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
            - "1433:1433"
        volumes:
            - ~/.mssql/data:/var/opt/mssql/data
            - ~/.mssql/log:/var/opt/mssql/log
            - ~/.mssql/shared:/var/opt/mssql/shared
        environment:
            SA_PASSWORD: "p@ssw0rd"
            ACCEPT_EULA: "Y"
